apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-logging
  labels:
    k8s-app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: {{.Values.kibana.image.Name}}:{{.Values.kibana.image.Tag}}
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: "{{ .Values.kibana.cpu.limits }}"
          requests:
            cpu: "{{ .Values.kibana.cpu.requests }}"
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
